language: python
python:
  - 3.5
  - 3.6
install:
  - pip install .
  - pip install -r requirements.txt
  - pip install POT
  - pip install black
before_script: cd tests/
script:
  - pytest
  - black --skip-string-normalization --check ../netrd
  - black --skip-string-normalization --check ../tests
