language: python
os:
 - linux
 - osx
 - windows
python:
  - 3.5
  - 3.6
install:
  - pip install .
  - pip install -r requirements.txt
  - pip install POT
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then pip install black; fi
before_script: cd tests/
script:
  - pytest
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then black --skip-string-normalization --check ../netrd; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then black --skip-string-normalization --check ../tests; fi
