language: python
matrix:
    include:
        - os: linux
          python: "3.5"

        - os: linux
          python: "3.6"

        - os: osx
          language: generic
          python: "3.5"

        - os: osx
          language: generic
          python: "3.6"

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update
    brew install openssl readline
    brew outdated pyenv || brew upgrade pyenv
    brew install pyenv-virtualenv
    pyenv install $PYTHON
    export PYENV_VERSION=$PYTHON
    export PATH="/Users/travis/.pyenv/shims:${PATH}"
    pyenv virtualenv venv
    source .pyenv/versions/venv/bin/activate
    python --version
    fi
install:
  - pip install .
  - pip install -r requirements.txt
  - pip install POT
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then pip install black; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then pip install pytest; fi
before_script: cd tests/
script:
  - pytest
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then black --skip-string-normalization --check ../netrd; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then black --skip-string-normalization --check ../tests; fi
